### ISSUE TITLE
Keep `i18n` dir in tarball for tests

### ISSUE THREAD

**Issue by tenzap** [kellpossible/cargo-i18n#104]
i18n-embed-fl's test suite requires the `i18n` folder which is not in the tarball distributed on crates.io

Would you please add them? We need them to package it for Debian.

**Comment by kellpossible** [comment]
@tenzap thanks for reporting, it should be fixed in the `i18n-embed-fl` version `0.6.6` now published

**Comment by tenzap** [comment]
I didn't try, but there may actually be the same problem with `i18n-embed`
