### ISSUE TITLE
`proc-macro-error` (dependency of `i18n-embed-fl`) is unmaintained

### ISSUE THREAD

**Issue by str4d** [kellpossible/cargo-i18n#113]
The last release of `proc-macro-error` was 3.5 years ago. It appears that the author of `proc-macro-error` has been AFK from their GitLab for around 2.5 years, which in particular means that `proc-macro-error` is not being updated to use `syn 2` (see e.g. https://gitlab.com/CreepySkeleton/proc-macro-error/-/merge_requests/35).

From the discussions around `proc-macro-error` there appear to be two maintained alternatives:
- [`proc-macro2-diagnostics`](https://crates.io/crates/proc-macro2-diagnostics)
- [`manyhow`](https://crates.io/crates/manyhow)

**Comment by kellpossible** [comment]
@str4d thanks for the heads up!
