### ISSUE TITLE
Use case question - Translating based on a "settings drop-down list"

### ISSUE THREAD

**Issue by psionikangel** [kellpossible/cargo-i18n#41]
Hi @kellpossible !

I have a use case question for you. I am working on adding localization on a rust app based on the very good `iced` UI framework. You can see the PR [here](https://github.com/casperstorm/ajour/pull/204) if you are curious, but the extra context shouldn't be necessary to answer my question.

Initially, I had used your library to translate the app based on the system locale (which worked wonderfully on both Mac OS and Windows). Then I tried to make the translation based on a "locale dropdown list" in the settings. (Meaning the fallback language would always be the default when the app loaded, but then the user could go in the settings, select an available language from the dropdown and the app would translate on the fly).

I have tried to achieve that using this example from your documentation

```
use std::rc::Rc;
use i18n_embed::{
    DesktopLanguageRequester, LanguageRequester,
    DefaultLocalizer, Localizer, fluent::FluentLanguageLoader     
};
use rust_embed::RustEmbed; use lazy_static::lazy_static;
use unic_langid::LanguageIdentifier;

#[derive(RustEmbed)]
#[folder = "i18n/ftl"] // path to localization resources
struct Translations;

const TRANSLATIONS: Translations = Translations {};

lazy_static! {
    static ref LANGUAGE_LOADER: FluentLanguageLoader = {
        // Usually you could use the fluent_language_loader!() macro
        // to pull values from i18n.toml configuration and current
        // module here at compile time, but instantiating the loader
        // manually here instead so the example compiles.
        let fallback: LanguageIdentifier = "en-US".parse().unwrap();
        FluentLanguageLoader::new("test", fallback)
    };
}

fn main() {
    let localizer = DefaultLocalizer::new(&*LANGUAGE_LOADER, &TRANSLATIONS);

    let localizer_rc: Rc<dyn Localizer> = Rc::new(localizer);

    let mut language_requester = DesktopLanguageRequester::new();
    language_requester.add_listener(Rc::downgrade(&localizer_rc));

    // Manually check the currently requested system language,
    // and update the listeners. When the system language changes,
    // this will automatically be triggered.
    language_requester.poll().unwrap();

    // continue on with your application
}
```

However, when trying it out I can't figure out why the translations aren't applied when I switch language in the settings. (After selecting the new language, the UI view refreshes and the UI elements are recreated, which in theory goes through the `tr!()` macro again and should produce UI elements with translated text).

The method I tried was to switch the current thread locale with
```
        let loc = Locale::new(&self.language_state.current_language_name);
        locale_config::Locale::set_current(loc.unwrap());
```

But when using the debugger I can confirm that it doesn't seem to trigger anything.

The base question that I have I guess would be:

**On what system event or other mechanism is the listener bound to in order to determine that the system requested language has changed?** 

And maybe a follow-up question would be : 

**Is the use-case that I'm trying to solve is at all supported by using your library?** (I'm a complete newbie to Rust, so it would be very possible that I just didn't understand the library well enough before settling on using it).

Sorry for the very long rambling, I hope the question I have make sense.

Regards,

**Comment by kellpossible** [comment]
Hi @psionikangel great news, I'm also interested to try out `iced` when it gets a few more features, and support for older systems!

> However, when trying it out I can't figure out why the translations aren't applied when I switch language in the settings. (After selecting the new language, the UI view refreshes and the UI elements are recreated, which in theory goes through the `tr!()` macro again and should produce UI elements with translated text).

By switching languages in the settings, do you mean in the system settings? I tried to implement support for detecting changes to system selected display language in the past, but closed the issue because it seemed difficult to implement on the desktop platform https://github.com/kellpossible/cargo-i18n/issues/30 I can't remember if I finished implementing support for it in the browser, but it was something that I had intended with the design. I should probably update the comment in that example to reflect the current state of support for this feature, as it's misleading, and I'm sorry if it caused some headaches! I'll do it soon when I update the library to the latest version of Fluent :slightly_smiling_face: 

In my applications, I've instead opted to make switching language at runtime an option in the application's settings.

**Comment by kellpossible** [comment]
I hope I've addressed some of these issues in the new `i18-embed` release `0.8.6` 00835512449c11277443ef935dc828d452ee9793

**Comment by psionikangel** [comment]
I was trying at runtime in the application's settings. So based on your comment, that should work?

**Comment by kellpossible** [comment]
@psionikangel yes it should work, but you'll have to do the change a different way, using the `i18n-embed` library directly via [select()](https://docs.rs/i18n-embed/0.9.3/i18n_embed/fn.select.html) or the [FluentLanguageLoader::load_languages() method (LanguageLoader implementation)](https://docs.rs/i18n-embed/0.9.3/i18n_embed/fluent/struct.FluentLanguageLoader.html#impl-LanguageLoader)

**Comment by casperstorm** [comment]
I'll take a stab at this @psionikangel – will use what you have done so far.

**Comment by kellpossible** [comment]
@psionikangel do you think the question is answered here okay? Or is there some more that could be done? I'll certainly make a mental note that when some GUI examples are added for this project to include a change language dropdown list

**Comment by psionikangel** [comment]
@kellpossible Yes, thank you for answering. You can close the issue. In the end, it was decided to postpone the translating feature because the UI framework mentionned above (iced) doesn't support all the charactersets that were needed for certain languages.

**Comment by kellpossible** [comment]
Just tried to make an example of this using iced, and ran into the same problem, do you know if there is a tracking issue for it in iced?

**Comment by psionikangel** [comment]
Yes, it is https://github.com/hecrj/iced/issues/103
