### ISSUE TITLE
i18n-embed (fluent): Visual artifacts around inserted arguments

### ISSUE THREAD

**Issue by fosskers** [kellpossible/cargo-i18n#44]
Hi there, I discovered these tools yesterday and am having a great time with them, thank you.

This morning I tried testing argument insertion via `fl!()`, like so:
```rust
    let msg = fl!(fll, "orphans-test", package = "thing");
    println!("{}", msg);
```
To my dismay, here it what appears in my terminal:
![2020-11-20-083316_956x511_scrot](https://user-images.githubusercontent.com/229679/99825107-71464f80-2b0b-11eb-8e31-1ee299fdafcc.png)

The Fluent I'm calling looks like this:
```
orphans-test = { $package } in the middle { $package } and at the end { $package }
```
Note that this also occurs when calling `FluentLanguageLoader::get_args` manually, so the problem isn't unique to `fl!`. It seems to occur regardless of which shell or terminal I use.

Thank you for any help you can offer.

**Comment by fosskers** [comment]
```rust
    println!("Bytes: {}", msg.len());
    println!("Chars: {}", msg.chars().count());
```
```
Bytes: 64
Chars: 52
```

**Comment by fosskers** [comment]
```rust
    for (i, c) in msg.chars().enumerate() {
        println!("{:02}: {}", i, c);
    }
```
<details>
<summary> Output </summary>
<pre>
<code>
00: ⁨
01: t
02: h
03: i
04: n
05: g
06: ⁩
07:  
08: i
09: n
10:  
11: t
12: h
13: e
14:  
15: m
16: i
17: d
18: d
19: l
20: e
21:  
22: ⁨
23: t
24: h
25: i
26: n
27: g
28: ⁩
29:  
30: a
31: n
32: d
33:  
34: a
35: t
36:  
37: t
38: h
39: e
40:  
41: e
42: n
43: d
44:  
45: ⁨
46: t
47: h
48: i
49: n
50: g
51: ⁩
</code>
The extra blanks here appear as boxes in my terminal.
</pre>
</details>

**Comment by fosskers** [comment]
And if it helps at all, here is how I'm initializing my loader:
```rust
#[derive(RustEmbed)]
#[folder = "i18n"]
struct Translations;

pub fn loader(lang: Option<LanguageIdentifier>) -> Result<FluentLanguageLoader, I18nEmbedError> {
    let loader = fluent_language_loader!();
    loader.load_languages(
        &Translations,
        &[lang.as_ref().unwrap_or_else(|| loader.fallback_language())],
    )?;
    Ok(loader)
}
```

**Comment by fosskers** [comment]
So there are 6 naughty chars (the blanks), and 12 more bytes than we expect, so they must be 2 bytes each and therefore not ASCII (as the code sample twice up shows).

**Comment by fosskers** [comment]
The bytes of the 6 bad chars:
1. `e2 81 a8`
2. `e2 81 a9`
3.  `e2 81 a8`
4. `e2 81 a9`
5. `e2 81 a8`
6. `e2 81 a9`

According to https://www.utf8-chartable.de/unicode-utf8-table.pl?start=8192&number=128, these two unicode values refer to:
```
U+2068 | ⁨ | e2 81 a8 | FIRST STRONG ISOLATE
U+2069 | ⁩ | e2 81 a9 | POP DIRECTIONAL ISOLATE
```
- [First Strong Isolate](http://www.unicode-symbol.com/u/2068.html)
- [Pop Directional Isolate](http://www.unicode-symbol.com/u/2069.html)

**Comment by fosskers** [comment]
Next I'm doing to test this with direct use of the `fluent` library and see what happens. Note that I've been running these in devel mode, so I believe RustEmbed grabs the files from the file system, and not from any embedded data.

**Comment by fosskers** [comment]
You're off the hook :) I see the same results when I use vanilla `fluent`. I'll report the issue to their repo now.

**Comment by kellpossible** [comment]
Hi thanks for reporting the issue and the pull request! I'm glad you've been enjoying using this library and I'll make sure to have a good look at these issues this week, hopefully tomorrow.
