### ISSUE TITLE
Multi-paragraph messages with CRLF ignore later paragraphs

### ISSUE THREAD

**Issue by str4d** [kellpossible/cargo-i18n#57]
This occurs on both `i18n-embed 0.9.4` and the current release (`0.10.1`). I believe this was caused by #36 being closed.

Minimal reproduction:
- https://github.com/str4d/rage/commit/8c67875fafb1fa9eaa072f53ddb342ed09e6faa1 upgrades `i18n-embed` from 0.9.3 to 0.9.4.
- Before that commit, all tests pass, including Windows: https://github.com/str4d/rage/runs/1678885056
- After that commit, Windows fails due to `fl!` not finding translation arguments, but all other tests pass: https://github.com/str4d/rage/runs/1685569886
- The specific fluent messages are here: https://github.com/str4d/rage/blob/8c67875fafb1fa9eaa072f53ddb342ed09e6faa1/age/i18n/en-US/age.ftl#L66-L96

**Comment by kellpossible** [comment]
Thanks @str4d I'll look into this today

**Comment by kellpossible** [comment]
It seems likely to be an upstream fluent bug, I'll try to make a minimal reproduction for them to report

**Comment by kellpossible** [comment]
This seems likely to be an upstream issue with `fluent` that I had assumed to be fixed but is still broken for this case, I'll report it there, and re-insert the work-around.

**Comment by kellpossible** [comment]
I have reported this as an upstream issue https://github.com/projectfluent/fluent-rs/issues/213 

As a quick workaround you can put indentation between the breaks, ensure that your editor doesn't delete them. I'll re-insert the previous workaround and push a new release soon.

**Comment by kellpossible** [comment]
Workaround now published in `i18n-embed` version `0.10.2`. Does this solve the problem for you @str4d ?

**Comment by str4d** [comment]
Yes, [the workaround fixes my Windows tests](https://github.com/str4d/rage/pull/187/commits/a4712dea4bcc05f68040580cdad674d6e13270ce). Thanks!

**Comment by kellpossible** [comment]
Awesome! I guess I'll close this one then :slightly_smiling_face:
