### ISSUE TITLE
i18n-embed-fl tries to load i18n.toml different from fluent_language_loader

### ISSUE THREAD

**Issue by Yesterday17** [kellpossible/cargo-i18n#60]
`fluent_language_loader` uses:
https://github.com/kellpossible/cargo-i18n/blob/ff4ee1d42a25c49a9d0190c22d75fa4cbe64578e/i18n-embed/i18n-embed-impl/src/lib.rs#L88

while `fl!` uses:
https://github.com/kellpossible/cargo-i18n/blob/ff4ee1d42a25c49a9d0190c22d75fa4cbe64578e/i18n-embed-fl/src/lib.rs#L290-L296

In workspaces, for example, a `sample-workspace` contains `sample-project`, `fluent_language_loader` tries to load `sample-workspace/i18n.toml`, while `fl!` tries to load `sample-workspace/sample-project/i18n.toml`.

**Comment by kellpossible** [comment]
Thanks for reporting this, I think the expected behaviour is what the `fl!` macro is doing, so I guess there's a bug with the logic in `fluent_language_loader`'s path resolution for `i18n.toml`. I'll hopefully look at it soon! Or would also appreciate a PR if you'd like to try and fix it.
