### ISSUE TITLE
Add custom functions to the bundles in FluentLanguageLoader?

### ISSUE THREAD

**Issue by kaj** [kellpossible/cargo-i18n#75]
I use `fluent_language_loader!()` to get a `FluentLanguageLoader`, which is used by the `fl!(...)` macro from the `i18n-embed-fl` crate.  Now I'd like to add a custom function to the bundles, but there seems to be now way to access them.  As the bundles are kept inside private field `language_config` there seems to be no way of doing this?

There is a method `set_use_isolating` that loops over the associated bundles and sets the value. Maybe an `add_function` method could be added in a similar way?  Or maybe a more generic function that does a callback for each associated bundle?

(If this sounds reasonable, I could try to provide implementation.  If adding functions is already possible some other way I'd be happy to hear that.)

**Comment by kellpossible** [comment]
@kaj thanks for getting in contact!

>  Now I'd like to add a custom function to the bundles

Can you explain a bit more what you mean by this? Do you want a way to modify what is in the bundles?

**Comment by kaj** [comment]
Sorry for being unclear.  I meant ["Functions in FTL" as described here](https://projectfluent.org/fluent/guide/functions.html).  I want to be able to write things like this in my `app.ftl` bundles:

```ftl
label = Message with { MYFUNCTION($value) } in it.
```

**Comment by kellpossible** [comment]
@kaj Thanks I understand now! Your suggestion to provide a generic function where we pass a callback with mutable access to each bundle seems like a good one, and in hindsight perhaps that's what I should have done with `set_use_isolating` too, we could deprecate it in favour of this. I'm happy to do this, but if you'd like to contribute let me know, it seems like a good first contribution to the project.

**Comment by kaj** [comment]
I made an attempt.  Seems to work as intended, though I'm not sure about docs, changelog etc.   Looking forward to review ...   :-)

**Comment by kellpossible** [comment]
@kaj thanks! I'll take a look at it tomorrow :slightly_smiling_face:

**Comment by kellpossible** [comment]
Released with `i18n-embed` version `0.13.1`
